apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "knowledgebase-slackbot.fullname" . }}
spec:
  secretName: {{ include "knowledgebase-slackbot.proxy-certificate-secret" . }}
  duration: {{ .Values.certificateDuration }}
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    kind: Issuer
    group: cert-manager.io
    name: {{ required "The name of the CA issuer must be set" .Values.certificateIssuer | quote }}
  dnsNames: {{ .Values.certificateDNSNames }}
