apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowledgebase-slackbot.fluent-bit-config" . }}
data:
  parsers.conf: |-
{{ include "knowledgebase-slackbot.fluentbit-parsers-conf" . | indent 4 }}
  fluent-bit.conf: |-
{{ include "knowledgebase-slackbot.fluentbit-conf" . | indent 4 }}
