apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowledgebase-slackbot.forward-channel-secret" . }}
type: Opaque
data:
  channel: {{ (required "Slack Question Forward Channel must be set" .Values.forwardChannel) | b64enc }}
