apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "knowledgebase-slackbot.ingest" . }}
  labels:
    app: knowledgebase
    component: ingest
spec:
  schedule: "0 0 * * *"
  jobTemplate:
{{ include "knowledgebase-slackbot.ingest-job-spec" . | indent 4 }}
