apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowledgebase-slackbot.folder-id-secret" . }}
type: Opaque
data:
  folder-id: {{ (required "Google Folder ID must be set" .Values.ingestFolderID) | b64enc }}
