apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowledgebase-slackbot.knowledgebase-configmap" . }}
data:
  settings.yaml: |-
{{ include "knowledgebase-slackbot.knowledgebase-config" . | indent 4 }}
