apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowledgebase-slackbot.metricbeat-config-configmap" . }}
data:
  metricbeat.yml: |-
{{ include "knowledgebase-slackbot.metricbeat-config" . | indent 4 }}
