apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowledgebase-slackbot.metricbeat-pod-name" . }}
  labels:
    app: knowledgebase
    component: metricbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowledgebase
      component: metricbeat
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/metricbeat-config-configmap.yaml") . | sha256sum }}
        checksum/certificates: {{ include (print $.Template.BasePath "/certificate.yaml") . | sha256sum }}
      labels:
        app: knowledgebase
        component: metricbeat
    spec:
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:8.12.2
        volumeMounts:
        - name: metricbeat-config
          mountPath: /usr/share/metricbeat/metricbeat.yml
          subPath: metricbeat.yml
          readOnly: true
        - name: certificates
          mountPath: /certificates
      volumes:
      - name: certificates
        secret:
          secretName: {{ include "knowledgebase-slackbot.proxy-certificate-secret" . }}
      - name: metricbeat-config
        configMap:
          name: {{ include "knowledgebase-slackbot.metricbeat-config-configmap" . }}
          items:
          - key: metricbeat.yml
            path: metricbeat.yml
