apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "knowledgebase-slackbot.logs-pvc" . }}
  labels:
    app: knowledgebase
    component: slackbot
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.logsVolumeSize }}
