apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowledgebase-slackbot.slackbot-tokens-secret" . }}
type: Opaque
data:
  app-token: {{ (required "Slack APP Token must be set" .Values.slackAppToken) | b64enc }}
  bot-token: {{ (required "Slack Bot Token must be set" .Values.slackBotToken) | b64enc }}
