apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowledgebase-slackbot.slackbot-pod-name" . }}
  labels:
    app: knowledgebase
    component: slackbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowledgebase
      component: slackbot
  template:
    metadata:
      labels:
        app: knowledgebase
        component: slackbot
    spec:
      containers:
      - name: slackbot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["python", "-m", "knowledge_base_gpt.apps.slackbot.slack_bot"]
        volumeMounts:
        - mountPath: "/db"
          name: embedding
          readOnly: true
        - mountPath: /metrics
          name: metrics
        env:
        - name: PERSIST_DIRECTORY
          value: "/db"
        - name: REDIS_HOST
          value: knowledgebase-redis
        - name: FORWARD_QUESTION_CHANNEL_NAME
          valueFrom:
            secretKeyRef:
              name: "{{ include "knowledgebase-slackbot.forward-channel-secret" . }}"
              key: channel
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ include "knowledgebase-slackbot.slackbot-tokens-secret" . }}"
              key: app-token
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ include "knowledgebase-slackbot.slackbot-tokens-secret" . }}"
              key: bot-token
        - name: METRICS_FILE
          value: /metrics/slackbot_metrics.log
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu: 1
            memory: 1Gi
      - name: proxy
        image: "docker.io/envoyproxy/envoy:{{ .Values.envoyProxyImageTag }}"
        volumeMounts:
        - name: proxy-config
          mountPath: /etc/envoy
        - name: proxy-certificates
          mountPath: /etc/envoy-certificates
        env:
        - name: ENVOY_UID
          value: "0"
        resources:
          limits:
            cpu: 1
            memory: 1Gi
      - name: fluent-bit
        image: "docker.io/fluent/fluent-bit:{{ .Values.fluentbitImageTag }}"
        command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit-config/fluent-bit.conf"]
        volumeMounts:
        - mountPath: /metrics
          name: metrics
        - name: fluent-bit-config
          mountPath: /fluent-bit-config
        resources:
          limits:
            cpu: 1
            memory: 1Gi
      volumes:
      - name: embedding
        persistentVolumeClaim:
          claimName: {{ include "knowledgebase-slackbot.embedding-pvc" . }}
      - name: metrics
        persistentVolumeClaim:
          claimName: {{ include "knowledgebase-slackbot.metrics-pvc" . }}
      - name: proxy-config
        configMap:
          name: {{ include "knowledgebase-slackbot.proxy-configmap" . }}
      - name: proxy-certificates
        secret:
          secretName: {{ include "knowledgebase-slackbot.proxy-certificate-secret" . }}
      - name: fluent-bit-config
        configMap:
          name: {{ include "knowledgebase-slackbot.fluent-bit-config" . }}
