stages:
- answer
- question
metric_fields:
- name: prompt_eval_count
  type: count
- name: eval_count
  type: count
- name: load_duration
  type: duration
- name: prompt_eval_duration
  type: duration
- name: eval_duration
  type: duration
- name: total_duration
  type: duration
buckets:
  count:
  - 50
  - 100
  - 300
  - 500
  - 1000
  - 2000
  - 5000
  duration:
  - 1000000000
  - 5000000000
  - 10000000000
  - 30000000000
  - 60000000000