- name: Verify all required parameters were set
  delegate_to: localhost
  run_once: true
  block:
  - name: Verify frontend_ingest_google_drive_folder_id was set
    ansible.builtin.assert:
      that: frontend_ingest_google_drive_folder_id | default("") | length > 0
      fail_msg: "Make sure to set frontend_ingest_google_drive_folder_id"
  - name: Slackbot checks
    when: frontend_provision_slackbot
    block:
    - name: Verify frontend_slack_app_token was set
      ansible.builtin.assert:
        that: frontend_slack_app_token | default("") | length > 0
        fail_msg: "Make sure to set frontend_slack_app_token"
    - name: Verify frontend_slack_bot_token was set
      ansible.builtin.assert:
        that: frontend_slack_bot_token | default("") | length > 0
        fail_msg: "Make sure to set frontend_slack_bot_token"
    - name: Verify frontend_forward_question_channel_name was set
      ansible.builtin.assert:
        that: frontend_forward_question_channel_name | default("") | length > 0
        fail_msg: "Make sure to set frontend_forward_question_channel_name"

- name: Installations
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true

- name: Installations
  ansible.builtin.include_tasks:
    file: setup_quadlets.yml
    apply:
      become: false
