- name: Installations
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true

- name: Installations
  ansible.builtin.include_tasks:
    file: setup_quadlets.yml
    apply:
      become: false
