- name: Create random string for the cookie secret
  ansible.builtin.set_fact:
    cookie_secret: "{{ lookup('community.general.random_string', override_special='-_', length=32, base64=true) }}"

- name: Create the kube secret for the cookie secret
  containers.podman.podman_secret:
    name: knowledgebase-oauth-proxy-cookie-secret
    state: present
    skip_existing: true
    data: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: knowledgebase-oauth-proxy-cookie-secret
      data:
        cookie-secret: "{{ cookie_secret }}"

- name: Create the kube secret for the client info
  containers.podman.podman_secret:
    name: knowledgebase-oauth-proxy-client-info
    state: present
    skip_existing: true
    data: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: knowledgebase-oauth-proxy-client-info
      data:
        client_id: "{{ frontend_oauth_client_id | b64encode }}"
        client_secret: "{{ frontend_oauth_client_secret | b64encode }}"
