- name: Create Quadlet directory
  ansible.builtin.file:
    path: "{{ frontend_quadlet_directory }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'

- name: Create template files list
  ansible.builtin.set_fact:
    _frontend_template_files_list: "{{ frontend_template_files_list_base }}"
    _frontend_services_list: "{{ [] }}"

- name: Add Slackbot files if needed
  ansible.builtin.set_fact:
    _frontend_template_files_list: "{{ _frontend_template_files_list + frontend_template_files_list_slackbot}}"
    _frontend_services_list: "{{ _frontend_services_list + frontend_services_list_slackbot }}"
  when: frontend_provision_slackbot

- name: Add WebUI Files
  ansible.builtin.set_fact:
    _frontend_template_files_list: "{{ _frontend_template_files_list + frontend_template_files_list_webui}}"
    _frontend_services_list: "{{ _frontend_services_list + frontend_services_list_webui }}"
  when: frontend_provision_gradio

- name: Setup secrets
  when: frontend_provision_slackbot or frontend_provision_gradio
  ansible.builtin.include_tasks: create_secrets.yml

- name: Create Quadlet files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ frontend_quadlet_directory }}/{{ item }}"
    mode: '0644'
  loop: "{{ _frontend_template_files_list }}"

- name: Copy the Google API service key file
  ansible.builtin.copy:
    src: "{{ frontend_ingest_google_api_service_key_file }}"
    dest: "{{ frontend_quadlet_directory }}/service_key.json"
    mode: '0644'
  when: (frontend_ingest_google_api_service_key_file | default('') | length) > 0

- name: Run daemon reload to make Quadlet create the service files
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: "Starting the requested services"
  ansible.builtin.systemd_service:
    state: started
    scope: user
    name: "{{ item }}.service"
  async: 1800
  poll: 0
  when: _frontend_services_list | length > 0
  loop: "{{ _frontend_services_list }}"
  register: service_start_async_results

- name: Wait for all services to start
  ansible.builtin.async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ service_start_async_results.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 180
  delay: 10
