- name: Verify all required parameters were set
  delegate_to: localhost
  run_once: true
  block:
  - name: Verify ollama_ingest_google_drive_folder_id was set
    ansible.builtin.assert:
      that: ollama_ingest_google_drive_folder_id | default("") | length > 0
      fail_msg: "Make sure to set ollama_ingest_google_drive_folder_id"
  - name: Verify ollama_slack_app_token was set
    ansible.builtin.assert:
      that: ollama_slack_app_token | default("") | length > 0
      fail_msg: "Make sure to set ollama_slack_app_token"
  - name: Verify ollama_slack_bot_token was set
    ansible.builtin.assert:
      that: ollama_slack_bot_token | default("") | length > 0
      fail_msg: "Make sure to set ollama_slack_bot_token"

- name: Installations
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true

- name: Configure Ollama Quadlet
  ansible.builtin.include_tasks:
    file: setup_ollama.yml
    apply:
      become: false
