- name: Create Quadlet directory
  ansible.builtin.file:
    path: "{{ ollama_quadlet_directory }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'

- name: Create Quadlet files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ollama_quadlet_directory }}/{{ item }}"
    mode: '0644'
  loop:
  - gradio.container

- name: Run daemon reload to make Quadlet create the service files
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Run the UI
  ansible.builtin.systemd_service:
    state: started
    scope: user
    name: gradio.service
  async: 1800
  poll: 60
