- name: Create Quadlet directory
  ansible.builtin.file:
    path: "{{ ollama_quadlet_directory }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'

- name: Create template files list
  ansible.builtin.set_fact:
    _ollama_template_files_list: "{{['ollama.container', 'ollama.network', 'ollama.volume']}}"
    _ollama_services_list: "{{ ['ollama'] }}"

- name: Add HAProxy files if needed
  ansible.builtin.set_fact:
    _ollama_template_files_list: "{{ _ollama_template_files_list + ['ollama-proxy.container', 'ollama-proxy-config.yml']}}"
    _ollama_services_list: "{{ _ollama_services_list + ['ollama-proxy'] }}"
  when: ollama_expose_secured_port

- name: Create Quadlet files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ollama_quadlet_directory }}/{{ item }}"
    mode: '0644'
  loop: "{{ _ollama_template_files_list }}"

- name: Run daemon reload to make Quadlet create the service files
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: "Starting the ollama services"
  ansible.builtin.systemd_service:
    state: started
    scope: user
    name: "{{ item }}.service"
  async: 1800
  poll: 60
  when: _ollama_services_list | length > 0
  loop: "{{ _ollama_services_list }}"

- name: Pull model
  ansible.builtin.command:
    cmd: "podman exec ollama ollama pull {{ ollama_model }}"
  async: 1800
  poll: 60
