- name: Create Quadlet directory
  ansible.builtin.file:
    path: "{{ ollama_quadlet_directory }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'

- name: Create Quadlet files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ollama_quadlet_directory }}/{{ item }}"
    mode: '0644'
  loop:
  - ollama.container
  - ollama.network
  - ollama.volume

- name: Run daemon reload to make Quadlet create the service files
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Start Ollama
  ansible.builtin.systemd_service:
    state: started
    scope: user
    name: ollama.service
  async: 1800
  poll: 60

- name: Pull model
  ansible.builtin.command:
    cmd: "podman exec ollama ollama pull {{ ollama_model }}"
  async: 1800
  poll: 60
