- name: Verify all required parameters were set
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - block:
    - name: Verify frontend_ingest_google_drive_folder_id was set
      ansible.builtin.assert:
        that: frontend_ingest_google_drive_folder_id | default("") | length > 0
        fail_msg: "Make sure to set frontend_ingest_google_drive_folder_id"
    - name: Slackbot checks
      when: frontend_provision_slackbot | default(true)
      block:
      - name: Verify frontend_slack_app_token was set
        ansible.builtin.assert:
          that: frontend_slack_app_token | default("") | length > 0
          fail_msg: "Make sure to set frontend_slack_app_token"
      - name: Verify frontend_slack_bot_token was set
        ansible.builtin.assert:
          that: frontend_slack_bot_token | default("") | length > 0
          fail_msg: "Make sure to set frontend_slack_bot_token"
      - name: Verify frontend_forward_question_channel_name was set
        ansible.builtin.assert:
          that: frontend_forward_question_channel_name | default("") | length > 0
          fail_msg: "Make sure to set frontend_forward_question_channel_name"

- name: Install Ollama backend
  hosts: ollama
  tasks:
  roles:
  - ollama
  - frontend
