- name: Verify all required parameters were set
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - block:
    - name: Check the issuer name was set
      ansible.builtin.assert:
        that: ollama_certificate_ca_issuer | default('') | length > 0
        fail_msg: ollama_certificate_ca_issuer must be set
    - name: Check the FQDN was set
      ansible.builtin.assert:
        that: ollama_fqdn | default('') | length > 0
        fail_msg: ollama_fqdn must be set
    - name: Check the certificate namespace is was set
      ansible.builtin.assert:
        that: ollama_certificate_namespace | default('') | length > 0
        fail_msg: ollama_certificate_namespace must be set

- name: Install Ollama backend
  hosts: ollama
  vars:
    ollama_expose_secured_port: True
  tasks:
  roles:
  - ollama
